In [12]:
# Dataset Creation

import numpy as np

X = np.array([1, 2, 3, 4, 5], dtype=float)
y = np.array([3, 5, 7, 9, 11], dtype=float)

print(X)
print(y)

[1. 2. 3. 4. 5.]
[ 3.  5.  7.  9. 11.]


In [13]:
# model

w = 0.0
b = 0.0

y_pred = w * X + b

print(y_pred)

[0. 0. 0. 0. 0.]


In [14]:
# calculate the loss
error = y - y_pred

loss = np.mean(error ** 2)

print("Predictions:", y_pred)
print("Error:", error)
print("Loss:", loss)

Predictions: [0. 0. 0. 0. 0.]
Error: [ 3.  5.  7.  9. 11.]
Loss: 57.0


In [5]:
# calculate gradients
n = len(X)

dw = (-2 / n) * np.sum(X * (y - y_pred))
db = (-2 / n) * np.sum(y - y_pred)

print("dw:", dw)
print("db:", db)

dw: -50.0
db: -14.0


In [6]:
learning_rate = 0.01

w = w - learning_rate * dw
b = b - learning_rate * db

print("New w:", w)
print("New b:", b)

New w: 0.5
New b: 0.14


In [7]:
# new predictions after one update
y_pred = w * X + b

print(y_pred)

[0.64 1.14 1.64 2.14 2.64]


In [8]:
# calculate loss again
loss = np.mean((y - y_pred) ** 2)

print("New loss:", loss)

New loss: 33.22959999999999


In [9]:
# automate the learning
import numpy as np

X = np.array([1, 2, 3, 4, 5], dtype=float)
y = np.array([3, 5, 7, 9, 11], dtype=float)

w = 0.0
b = 0.0

learning_rate = 0.01
epochs = 1000

for epoch in range(epochs):

    # Forward pass
    y_pred = w * X + b

    # Loss
    loss = np.mean((y - y_pred) ** 2)

    # Gradients
    n = len(X)

    dw = (-2 / n) * np.sum(X * (y - y_pred))
    db = (-2 / n) * np.sum(y - y_pred)

    # Update
    w = w - learning_rate * dw
    b = b - learning_rate * db

    if epoch % 100 == 0:
        print(
            f"Epoch {epoch}: "
            f"Loss={loss:.4f}, "
            f"w={w:.4f}, "
            f"b={b:.4f}"
        )

Epoch 0: Loss=57.0000, w=0.5000, b=0.1400
Epoch 100: Loss=0.0159, w=2.0815, b=0.7058
Epoch 200: Loss=0.0081, w=2.0581, b=0.7903
Epoch 300: Loss=0.0041, w=2.0414, b=0.8505
Epoch 400: Loss=0.0021, w=2.0295, b=0.8935
Epoch 500: Loss=0.0011, w=2.0210, b=0.9241
Epoch 600: Loss=0.0005, w=2.0150, b=0.9459
Epoch 700: Loss=0.0003, w=2.0107, b=0.9614
Epoch 800: Loss=0.0001, w=2.0076, b=0.9725
Epoch 900: Loss=0.0001, w=2.0054, b=0.9804


In [11]:
# predictions after training
x_new = 10

prediction = w * x_new + b

print("Prediction:", prediction)

Prediction: 21.02479568986508


# Stage 2: Matrix Linear Regression

In [15]:
# generate a 2d dataset
import numpy as np

X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
], dtype=float)

y = np.array([3, 5, 7, 9, 11], dtype=float)

print(X.shape)
print(y.shape)

(5, 1)
(5,)


In [16]:
# initialize weights and bias
W = np.array([[0.0]])
b = 0.0

# Predictions
y_pred = X @ W + b

print(y_pred)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [18]:
X = np.array([
    [1, 50],
    [2, 55],
    [3, 65],
    [4, 70],
    [5, 80]
], dtype=float)

In [22]:
W = np.array([
    [0.5],
    [0.2]
])

b = 1.0

# predictions
y_pred = X @ W + b
print(y_pred)

[[11.5]
 [13. ]
 [15.5]
 [17. ]
 [19.5]]


In [23]:
# Complete code 
import numpy as np

# Dataset
X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
], dtype=float)

y = np.array([
    [3],
    [5],
    [7],
    [9],
    [11]
], dtype=float)

# Parameters
W = np.zeros((1, 1))
b = 0.0

learning_rate = 0.01
epochs = 1000

n = X.shape[0]

for epoch in range(epochs):

    # Forward pass
    y_pred = X @ W + b

    # Error
    error = y - y_pred

    # Loss
    loss = np.mean(error ** 2)

    # Gradients
    dW = (-2 / n) * X.T @ error
    db = (-2 / n) * np.sum(error)

    # Update
    W = W - learning_rate * dW
    b = b - learning_rate * db

    if epoch % 100 == 0:
        print(
            f"Epoch {epoch}: "
            f"Loss={loss:.4f}, "
            f"W={W.ravel()[0]:.4f}, "
            f"b={b:.4f}"
        )

Epoch 0: Loss=57.0000, W=0.5000, b=0.1400
Epoch 100: Loss=0.0159, W=2.0815, b=0.7058
Epoch 200: Loss=0.0081, W=2.0581, b=0.7903
Epoch 300: Loss=0.0041, W=2.0414, b=0.8505
Epoch 400: Loss=0.0021, W=2.0295, b=0.8935
Epoch 500: Loss=0.0011, W=2.0210, b=0.9241
Epoch 600: Loss=0.0005, W=2.0150, b=0.9459
Epoch 700: Loss=0.0003, W=2.0107, b=0.9614
Epoch 800: Loss=0.0001, W=2.0076, b=0.9725
Epoch 900: Loss=0.0001, W=2.0054, b=0.9804


In [24]:
# Print the latest weights and bias
print("Final W:", W)
print("Final b:", b)

Final W: [[2.00388058]]
Final b: 0.9859898664422495


In [25]:
# prediction on new data
X_new = np.array([
    [6],
    [10],
    [20]
], dtype=float)

predictions = X_new @ W + b

print(predictions)

[[13.00927336]
 [21.02479569]
 [41.06360151]]
