In [2]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.shape)
print(A.T)

(2, 3)
[[1 4]
 [2 5]
 [3 6]]


# Matrix Addition

Matrices can be added **only when their dimensions match**.

$$
A=
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
$$

$$
B=
\begin{bmatrix}
5&6\\
7&8
\end{bmatrix}
$$

Then:

$$
A+B=
\begin{bmatrix}
1+5&2+6\\
3+7&4+8
\end{bmatrix}
=
\begin{bmatrix}
6&8\\
10&12
\end{bmatrix}
$$

Element-by-element, just like vector addition.

---

# Scalar Multiplication of Matrix

Given:

$$
A=
\begin{bmatrix}
1&2\\
3&4
\end{bmatrix}
$$

then:

$$
2A=
\begin{bmatrix}
2&4\\
6&8
\end{bmatrix}
$$

Every element gets multiplied by the scalar.

---

# Matrix Transpose

Transpose essentially **swaps rows and columns**.

$$
A=
\begin{bmatrix}
1&2&3\\
4&5&6
\end{bmatrix}
$$

Then:

$$
A^T=
\begin{bmatrix}
1&4\\
2&5\\
3&6
\end{bmatrix}
$$

Therefore:

$$
(2\times3)\rightarrow(3\times2)
$$

In NumPy:

```python
A.T
```

# Matrix Multiplication
### The key rule 🔑

If:

$$
A_{m×n}B_{n×p}
$$

then:

$$
AB_{m×p}
$$

In [2]:
# Identity matrix
import numpy as np

I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Inverse of a matrix
A = np.array([
    [2, 0],
    [0, 3]
])

np.linalg.inv(A)

array([[0.5       , 0.        ],
       [0.        , 0.33333333]])

In [3]:
# Determinant of a matrix
A = np.array([
    [2, 3],
    [1, 4]
])

print(np.linalg.det(A))

5.000000000000001


# 6. Eigenvalues & Eigenvectors

This sounds scary, but the core idea is simple.

A matrix transforms a vector:

$$
Av
$$

Usually, the vector changes **both direction and magnitude**.

But some special vectors only get **scaled**:

$$
Av=\lambda v
$$

Where:

* \(v\) = **eigenvector**
* \(lambda\) = **eigenvalue**

### Example

$$
A=
\begin{bmatrix}
2&0\\
0&3
\end{bmatrix}
$$

Take:

$$
v=
\begin{bmatrix}
1\\
0
\end{bmatrix}
$$

Then:

$$
Av=
\begin{bmatrix}
2\\
0
\end{bmatrix}
=
2v
$$

So:

* \(v=[1,0]\) is an eigenvector
* \(lambda=2\) is its eigenvalue

Another eigenvector:

$$
v=
\begin{bmatrix}
0\\1
\end{bmatrix}
$$

gives:

$$
Av=
\begin{bmatrix}
0\\3
\end{bmatrix}
=3v
$$

So eigenvalue = 3.

## Orthogonality & Projections → PCA Connection

You've already learned:

$$
a\cdot b=0
$$

means vectors are orthogonal.

And projection:

$$
proj_b(a)=
\frac{a\cdot b}{b\cdot b}b
$$

# 10. Matrix Math → Neural Networks → Transformers

Now connect the entire thing.

A neural network layer:

$$
Z=XW+b
$$

Then:

$$
A=f(Z)
$$

where \(f\) is an activation function.

Multiple layers:

$$
X
\rightarrow XW_1+b_1
\rightarrow f()
\rightarrow W_2
\rightarrow f()
\rightarrow ...
$$

Transformers take matrix operations much further.

For attention:

$$
Q=XW_Q
$$

$$
K=XW_K
$$

$$
V=XW_V
$$

Then:

$$
Attention(Q,K,V)
=
softmax\left(\frac{QK^T}{\sqrt{d_k}}\right)V
$$