# Installing Numpy

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b

In [ ]:
# useful constructs in numpy
print(np.zeros(5)) # print an array of zeros

print(np.ones(5)) # print an array of ones

print(np.arange(0, 10, 2)) # print an array of numbers from 0 to 10 with a step of 2

print(np.linspace(2, 10, 5)) # print an array of 5 numbers from 2 to 10


In [ ]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#check the shape of the array
np.shape(x)

# check dimensions of the array
np.ndim(x)

#check it's size
np.size(x)

#indexing
print(x[0, 1]) # get the element at row 0 and column 1

#slicing
print(x[0, 1:3]) # get the elements at row 0 and columns 1 and 2

In [ ]:
# Reshaping
x=np.array([1,2,3,4,5,6])

print(f"Initial shape of x: {x.shape}")

# Reshape the array to a 2x3 matrix
x = x.reshape(2, 3)
print(f"new array after reshaping: {x}")
print(f"Shape of x after reshaping: {x.shape}")

In [ ]:
#check the dtype of the array
x = np.array([1, 2, 3])

x.dtype

# Element wise operations (Vectorized Computation)

In [ ]:
x = np.array([1, 2, 3])

print(x * 2) # multiply each element by 2

print(x + 2) # add 2 to each element

print(x ** 2) # square each element


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr.shape)
print(arr.ndim)
print(arr.size)


print(arr[0,1])
print(arr[1,:])
print(arr[:,0])


arr = np.arange(1, 13)

print(np.reshape(arr, (3, 4))) # reshape to 3 rows and 4 columns

data = np.array([
    [25, 50000, 1],
    [30, 60000, 0],
    [35, 80000, 1],
    [40, 90000, 0]
])

x = data[:, :-1]  # features (all columns except the last one)
y = data[:, -1]   # target (last column)


x = np.array([1, 2, 3, 4, 5, 6])

x.reshape(2, -1)

## Vectorization

In [ ]:
x = np.array([1, 2, 3, 4])

print(f"add 2 to each element: {x + 2}")
print(f"multiply each element by 2: {x * 2}")
print(f"square each element: {x ** 2}")
print(f"subtract 1 from each element: {x - 1}")
print(f"divide each element by 2: {x / 2}")

In [ ]:
# agreegation 
print(np.sum(x)) # sum of all elements
print(np.mean(x)) # mean of all elements
print(np.median(x)) # median of all elements
print(np.std(x)) # standard deviation of all elements
print(np.var(x)) # variance of all elements
print(np.min(x)) # minimum of all elements
print(np.max(x)) # maximum of all elements
print(f"take the square root of each element: {np.sqrt(x)}")
print(f"take the exponential of each element: {np.exp(x)}")
print(f"take the natural logarithm of each element: {np.log(x)}")
print(f"take the sine of each element: {np.sin(x)}")
print(f"take the cosine of each element: {np.cos(x)}")
print(f"take the tangent of each element: {np.tan(x)}")

In [50]:
# Axis operations

x=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.sum(x, axis=0)) # sum of all elements along axis 0
print(np.sum(x, axis=1)) # sum of all elements along axis 1

[12 15 18]
[ 6 15 24]


In [ ]:
# Boolean Masking
x = np.array([10, 20, 30, 40, 50])

print(x > 25) # print a boolean array where each element is True if the corresponding element in x is greater than 25, and False otherwise

print(x[x > 25]) # print the elements in x that are greater than 25

print(x[(x > 20) & (x < 50)]) # print the elements in x that are greater than 20 and less than 50

In [53]:
# test

x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

x.sum(axis=0)
x.sum(axis=1)
x.mean(axis=0)


scores = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [90, 95, 85]
]) #3 row is students and 3 columns is subjects

print(f"avg score of each student: {np.mean(scores, axis=1)}")
print(f"avg score of each subject: {np.mean(scores, axis=0)}")
print(f"student with avg score greater than 80: {np.where(np.mean(scores, axis=1) >= 80)}")

avg score of each student: [80.         73.33333333 90.        ]
avg score of each subject: [76.66666667 83.33333333 83.33333333]
student with avg score greater than 80: (array([0, 2]),)


In [56]:
# Dot product

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

A @ B

array([[19, 22],
       [43, 50]])

In [58]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

print(A.shape)
print(B.shape)

print(A @ B) # dot product of A and B

print(B @ A) # dot product of B and A

print(A.T) # transpose of A

(2, 3)
(3, 2)
[[220 280]
 [490 640]]
[[ 90 120 150]
 [190 260 330]
 [290 400 510]]
[[1 4]
 [2 5]
 [3 6]]
